apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentry-cron
  name: sentry-cron
  namespace: sentry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentry-cron
  template:
    metadata:
      labels:
        app: sentry-cron
    spec:
      containers:
      - name: sentry-cron
        image: 192.168.1.108:5000/basic/sentry:8.22-onbuild
        imagePullPolicy: IfNotPresent
        args: ["run", "cron"]
        ports:
          - containerPort: 9000
        env:
          - name: SENTRY_SECRET_KEY
            value: "!_-9g8+6(6i8092ev-s38%q^gcdsm+e_+j1mqu+%qq*i1zd*ol"
          - name: SENTRY_POSTGRES_HOST
            value: sentry-postgresql
          - name: SENTRY_POSTGRES_PORT
            value: "5432"
          - name: SENTRY_DB_USER
            value: "sentry"
          - name: SENTRY_DB_NAME
            value: "sentry"
          - name: SENTRY_DB_PASSWORD
            value: "ymzndl33SNwdm"
          - name: SENTRY_REDIS_HOST
            value: sentry-redis
          - name: SENTRY_REDIS_PASSWORD
            value: "L9Ut7625E0dDdgf"
          - name: SENTRY_REDIS_PORT
            value: "6379"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: sentry-data
            mountPath: /var/lib/sentry/files
      imagePullSecrets:
        - name: harborsecretname
      volumes:
      - name: sentry-data
        hostPath:
          path: /data/container/sentry/cron
